# Generated by Django 2.1.15 on 2020-10-28 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='flood_od',
            new_name='floor_id',
        ),
    ]
