# Generated by Django 2.1.15 on 2020-11-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatmaps',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.Rooms'),
            preserve_default=False,
        ),
    ]
