# Generated by Django 2.1.15 on 2020-10-24 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floors',
            name='building_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Buildings'),
        ),
        migrations.AlterField(
            model_name='heatmaps',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Users'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='floor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Floors'),
        ),
    ]
