# Generated by Django 2.1.15 on 2020-10-28 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201027_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heatmaps',
            old_name='user_id',
            new_name='user',
        ),
    ]
