# Generated by Django 2.1.15 on 2020-10-28 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201027_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floors',
            old_name='building_id',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='floor_id',
            new_name='floor',
        ),
    ]
